name: CI

on:
    push:
        branches:
            - main
            - master
    pull_request: {}

concurrency:
    group: ci-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    test:
        name: 'Tests'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: volta-cli/action@v1
              with:
                  node-version: 18.x
                  yarn-version: 1.x
            - name: Install Dependencies
              run: yarn install
            - name: Lint
              run: yarn lint
            - name: Run Tests
              run: yarn test
